### ISSUE TITLE
Persistent results

### ISSUE THREAD

**Issue by Hipapheralkus** [hackvertor/taborator#7]
Hi,
whenever by Burp Suite crashes (usually because of other extensions), I don't want to loose the results I already have in the tab; nor do I want to loose those interactions, which didn't yet arrive. Could you perhaps implement some "autosave" or persistent storage of collaborator strings, so that people wouldn't loose their interactions?
Thanks

**Comment by hackvertor** [comment]
Taborator does store interactions in the project file but requires a clean shutdown because it hooks the unload extension event in Burp. I did add an export interactions button that allows you to save them to disk. I don't really want to add code that saves interactions regularly as it would affect performance.
